apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - namespacee.yaml

  - grafana/configmap.yaml
  - grafana/deployment.yaml
  - grafana/service.yaml

  - prometheus/configmap.yaml
  - prometheus/deployment.yaml
  - prometheus/service.yaml

  - loki/configmao.yaml
  - loki/deployment.yaml
  - loki/service.yaml

  - temp/configmap.yaml
  - tempo/deployment.yaml
  - tempo/service.yaml

  - otel-collector/configmap.yaml
  - otel-collector/deployment.yaml
  - otel-collector/service.yaml
